#!/bin/bash
RPATH="-I../lib"
for d in HilinkModem SerialModem HelperClasses; do
  RPATH="$RPATH -I../../$d/lib"
done
for d in activesupport-3.1.1 i18n-0.6.0 json-1.4.6 multi_json-1.0.3; do
  RPATH="$RPATH -I../../QooxView/libs/$d/lib"
done
ruby $RPATH $1
